services:
  api:
    build:
      context: ./sgmi_api/
      dockerfile: Dockerfile
    environment:
      - RAILS_ENV=development
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      postgresql:
        condition: service_healthy
    develop:
      watch:
        - action: rebuild
          path: .

  postgresql:
    image: postgres:18.0-alpine3.22
    secrets:
      - db-password
    environment:
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
    volumes:
      - db_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    healthcheck:
      test: pg_isready -U postgres -h 127.0.0.1
      interval: 5s

  web:
    build:
      context: .
      dockerfile: sgmi_frontend/Dockerfile.dev
    depends_on:
      - api
    volumes:
      - ./sgmi_frontend:/app
      - web_node_modules:/app/node_modules
    ports:
      - "5173:5173"

volumes:
  db_data:
  web_node_modules:

secrets:
  db-password:
    file: sgmi_api/db/password.txt
